### PR TITLE
Add queries for each credential

### PR DESCRIPTION
**Pull request by jameseaster**
#### _Resolves - allows visibility into credential queries_

---

### What kind of change does this PR introduce?

- Credential query update.

<br/>

### What is the current behavior?

- Queries are created from credentials separate from vc-examples.

<br/>

### What is the new behavior?

- Creates visibility into each credentials's query for its verification.
- Allows for multiple queries per credential to showcase different kinds of queries.

<br/>

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

<br/>

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
I think it's good to have this -- not sure if we'll want to refactor / reorganize in some other way as we go, but we can figure that out.

**Review by BigBlueHat — APPROVED** [review]
Great to have these examples available!

**Comment by BigBlueHat** [comment]
@jameseaster I resolved the CHANGELOG conflict here on GitHub, and apparently made things worse... 🤦  Sorry about that...let me know if you want me to clean it up locally.

**Comment by jameseaster** [comment]
@BigBlueHat No worries! I rebased and pushed, we should have a single line git history now

**Review by msporny — APPROVED** [review]

**Pull request merged**
