### PR TITLE
Fix Movie Ticket address issue; support VCDMv2.

### LINKED ISSUE #11: movie ticket address
https://github.com/digitalbazaar/chapi-playground/issues/41#issue-1421665452

### PR DESCRIPTION
**Pull request by BigBlueHat**
Fixes #11.

### CODE REVIEW

**Comment by BigBlueHat** [comment]
@dlongley I added `image` to the query to make these easier to find (especially when using selective disclosure), but I'm not sure that's necessarily a good idea (...when using selective disclosure). Maybe there's just more UI needed on the Wallet side to differentiate between what is found and what is to be shared?

**Review by tminard — APPROVED** [review]

**Review by dlongley — APPROVED** [review]
Yeah, I don't think including `image` is the right thing to do in the query. We can do it temporarily if necessary, but wallets should do a good job of showing the user what their choices are and what information is being shared -- and this doesn't mean that they can't show something that isn't being shared (like an image) to help with selection.

**Comment by BigBlueHat** [comment]
> Yeah, I don't think including `image` is the right thing to do in the query. We can do it temporarily if necessary, but wallets should do a good job of showing the user what their choices are and what information is being shared -- and this doesn't mean that they can't show something that isn't being shared (like an image) to help with selection.

Yeah. It felt like something we needed to fix in Veres Wallet not here. I'll remove that from the query then, and repush.

**Comment by BigBlueHat** [comment]
> When is it appropriate to retire one credential as another is brought on?

I'd expect we'll be supporting both the VC v1.1 and VC v2 examples for some time. There's definitely some UI work we need to do to make these clearer and more manageable--i.e. this is the first of many VC v2 examples...

> Do we want to keep the list of example credentials curated?

Yes. We need more UI options for doing that.

> Do we care if it becomes verbose?

Yes. See above. 😉 

> Is it confusing for users to see a v1 and v2 of the same credential?

Yes. See above, some more. 😜 

Folks already have VC v1.1 examples in their demo wallets, so we need to provide ways to interact with them and to help folks testing to know their systems can support bot VC v1.1 and v2 simultaneously. I'd like to introduce tabs or something for switching between the groups, but this was the fastest current way to get at least one VC v2 credential into the site. I'd rather not delay too long on UX reworking...but also don't want to put that off much longer. Happy to discuss more!

**Pull request merged**
