### PR TITLE
Update EAD

### PR DESCRIPTION
**Pull request by jameseaster**
#### _Resolves - add more detail & contexts to EAD_

---

### What kind of change does this PR introduce?

- EAD credential update.

<br/>

### What is the current behavior?

- More information needed for EAD example.

<br/>

### What is the new behavior?

- More credential subject values, types, and context are added from the [W3C Citizenship Vocabulary v2.0 example](https://w3c-ccg.github.io/citizenship-vocab/#full-employment-authorization-document-example)

<br/>

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

<br/>

### How has this been tested?

- Credential has been issued and viewed locally.

<br/>

### Screenshots: n/a

### CODE REVIEW

**Comment by jameseaster** [comment]
For reference:

> SVG with values
>
> svg

**Comment by BigBlueHat** [comment]
Font issues fixed and background opacity improved.
image

Dates could use to be formatted here also...

**Review by BigBlueHat — APPROVED** [review]
@jameseaster could you 👍 this when you're able? Thanks!

**Comment by jameseaster** [comment]
LGTM!

**Comment by davidlehn** [comment]
1.18MB json, 735KB svg.  Any chance for optimization?

**Comment by BigBlueHat** [comment]
@davidlehn shrunk it a bit, but most other optimizations would take significant time...which I no longer have (at the moment).

@jameseaster give this one more test, and I think it should be ready.

**Comment by jameseaster** [comment]
@BigBlueHat Unfortunately, the image does not render in the wallet b/c the code is expecting a url in render method.

**Comment by davidlehn** [comment]
- The data url likely needs url encoded raw svg.
- Also try svo on the source (which might mess up the templating).
- Should the headshot be centered in the images above?

**Comment by jameseaster** [comment]
Rendered locally with the compressed SVG stored in template - LGTM

Thanks @BigBlueHat!

**Comment by BigBlueHat** [comment]
> * Should the headshot be centered in the images above?

ugh. yes. I keep forgetting to do that...

**Comment by BigBlueHat** [comment]
@jameseaster image scooched. This should be ready.

**Pull request merged**
