### PR TITLE
Add back and barcode only renderMethods.

### PR DESCRIPTION
**Pull request by BigBlueHat**

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
These LGTM ... I don't have a PDF417 scanner in my eyes to check what's in there, but assume it matches the front of the example card.

**Comment by BigBlueHat** [comment]
@wes-smith can you confirm that the PDF417 works for your toolchain? It's the "valid" one we used in the other examples.

**Comment by wes-smith** [comment]
@BigBlueHat confirmed

**Review by wes-smith — CHANGES_REQUESTED** [review]
The PDF417 is an outdated VCB - use [this](https://w3c-ccg.github.io/vc-barcodes/#example-bytes-from-a-pdf417-including-an-encoded-utopia-driver-s-license-vcb). In addition, data in the PDF417 does not match data in credential.json (e.g. document_number does not match the 'DAQ' field).

**Review by msporny — APPROVED** [review]

**Review by wes-smith — APPROVED** [review]

**Pull request merged**
